export declare enum OrderStatus {
    QUEUED = "QUEUED",
    SCHEDULED = "SCHEDULED",
    PROCESSING = "PROCESSING",
    READY = "READY",
    COLLECTED = "COLLECTED",
    CANCELLED = "CANCELLED"
}
export declare enum NotificationType {
    ORDER_PLACED = "ORDER_PLACED",
    ORDER_ACCEPTED = "ORDER_ACCEPTED",
    ORDER_READY = "ORDER_READY",
    ORDER_CANCELLED = "ORDER_CANCELLED",
    NEW_ORDER = "NEW_ORDER",
    WALLET_TOPUP = "WALLET_TOPUP",
    WALLET_DEDUCTED = "WALLET_DEDUCTED",
    SHOP_APPROVED = "SHOP_APPROVED",
    SHOP_REJECTED = "SHOP_REJECTED",
    SHOP_SUSPENDED = "SHOP_SUSPENDED",
    STAFF_ASSIGNED = "STAFF_ASSIGNED",
    LOW_BALANCE = "LOW_BALANCE"
}
